#+title: Hanoi Towers 2
* Ханойские башни 2
Головоломка <<Ханойские башни>> состоит из трёх стержней, пронумеруем их слева направо: 1, 2 и 3.
Также в головоломке используется стопка дисков с отверстием посередине.
Радиус дисков уменьшается снизу вверх.
Изначально диски расположены на левом стержне (стержень 1), самый большой диск находится внизу.
Диски в игре перемещаются по одному со стержня на стержень.
Диск можно надеть на стержень, только если он пустой или верхний диск на нём большего размера, чем перемещаемый.
Цель головоломки — перенести все диски со стержня 1 на стержень 3.

Немного изменим правила.
Теперь головоломка состоит из четырех стержней, а цель головоломки — перенести все диски со стержня 1 на стержень 4.
 Найдите минимальное количество ходов, за которое можно решить головоломку.

** Формат ввода
В первой строке задано одно число n (3≤n≤10) — количество дисков на первой башне.
** Формат вывода
В единственной строке выведите ответ на задачу.

* Примеры

** Пример 1
*** Ввод
#+begin_src
3
#+end_src
*** Вывод
#+begin_src
5
#+end_src

** Пример 2
*** Ввод
#+begin_src
4
#+end_src
*** Вывод
#+begin_src
9
#+end_src

** Пример 3
*** Ввод
#+begin_src
5
#+end_src
*** Вывод
#+begin_src
13
#+end_src
