#+title: Hanoi Towers
* Ханойские башни
Головоломка <<Ханойские башни>> состоит из трёх стержней, пронумеруем их слева направо: 1, 2 и 3. Также в головоломке используется стопка дисков с отверстием посередине. Радиус дисков уменьшается снизу вверх. Изначально диски расположены на левом стержне (стержень 1), самый большой диск находится внизу. Диски в игре перемещаются по одному со стержня на стержень. Диск можно надеть на стержень, только если он пустой или верхний диск на нём большего размера, чем перемещаемый. Цель головоломки — перенести все диски со стержня 1 на стержень 3.
Требуется найти последовательность ходов, которая решает головоломку <<Ханойские башни>>.

** Формат ввода
В первой строке задано одно число n (3≤n≤10) — количество дисков на первой башне.
** Формат вывода
В первой строке выведите количество операций k.
В следующих k строках выведите по два числа в каждой, x_i, y_i(1≤x_i,y_i≤3) — переместить верхний диск со стержня x_i на стержень y_i.

* Примеры

** Пример 1
*** Ввод
#+begin_src
3
#+end_src
*** Вывод
#+begin_src
7
1 3
1 2
3 2
1 3
2 1
2 3
1 3
#+end_src

** Пример 2
*** Ввод
#+begin_src
4
#+end_src
*** Вывод
#+begin_src
15
1 2
1 3
2 3
1 2
3 1
3 2
1 2
1 3
2 3
2 1
3 1
2 3
1 2
1 3
2 3
#+end_src

** Пример 3
*** Ввод
#+begin_src
5
#+end_src
*** Вывод
#+begin_src
31
1 3
1 2
3 2
1 3
2 1
2 3
1 3
1 2
3 2
3 1
2 1
3 2
1 3
1 2
3 2
1 3
2 1
2 3
1 3
2 1
3 2
3 1
2 1
2 3
1 3
1 2
3 2
1 3
2 1
2 3
1 3
#+end_src
